---
- name: Deploy Flask web app
  hosts: f1
  become: yes



tasks:
  - name: Add a default Ubuntu repo
    apt_repository:
      repo: 'deb http://archive.ubuntu.com/ubuntu focal main'
      state: present 
 
  - name: Install required packages
    package:
      name:
        - python3
        - python3-pip
    state: present


  - name: Start Flask web app as a service
    copy:
      src: flasktest.py
      dest: /var/www/flaskweb
    become: yes
    
     - name: Start Flask web app as a service
    copy:
      src: app.py
      dest: /var/www/flaskweb
    become: yes


    - name: Clone the repository
      git:
        repo: 
        dest: /opt/Flaskweb
     
    - name: Install Flask and its dependencies
      pip:
        name: flask
        virtualenv: /opt/flasktest
        chdir: /opt/flaskweb
    
    

    command: |
      cd /var/www/
      nohup python3 flasktest.py &
    become: yes

   - name: Start the Flask web app
      command: /opt/flask-env/bin/python3 /opt/flaskweb/flasktest.py
      async: 1
      poll: 0
