---
- name: Deploy Flask web app
  hosts: f1
  become: yes



tasks:
  - name: Add a default Ubuntu repo
    apt_repository:
      repo: 'deb http://archive.ubuntu.com/ubuntu focal main'
      state: present 
 
  - name: Install required packages
    package:
      name:
        - python3
        - python3-pip
    state: present


  - name: Start Flask web app as a service
    copy:
      src: app.py
      dest: /var/www/app.py
    become: yes

    command: |
      cd /var/www/
      nohup python3 app.py &
    become: yes

  

    command: |
      systemctl restart nginx
      systemctl enable nginx
    become: yes
