---
- name: Deploy Flask web app
  hosts: F1
  become: yes

  tasks:
  - name: Add a default Ubuntu repo
    apt_repository:
      repo: 'deb http://archive.ubuntu.com/ubuntu focal main'
      state: present 
 
  - name: Install required packages
    package:
        - python3
        - python3-pip
    state: present

  - name: Clone the repository
    git:
      repo: https://github.com/jessyewoma/Flaskweb.git
      dest: /opt/Flaskweb

  - name: Install Flask and its dependencies
    pip:
      name: flask
      virtualenv: /var/www/flasktest.env
      chdir: /opt/flaskweb

  - name: Start the Flask web app
    command: /var/www/flasktest.env/bin/python3 /opt/flaskweb/flasktest.py
    async: 1
    poll: 0
